version: "3"

tasks:
  migration-down:
    desc: "Run migration down"
    cmds:
      - go run ./cmd/migrator/main.go -host=localhost -port=5432 -login=kirill -password=pass123 -db=ozon -path=./migrations -mode=down

  migration-up:
    desc: "Run migration up"
    cmds:
      - go run ./cmd/migrator/main.go -host=localhost -port=5432 -login=kirill -password=pass123 -db=ozon -path=./migrations -mode=up


  db-start:
    desc: "Start postgres on docker"
    cmds:
      - sudo docker run --rm --name pgdocker -e POSTGRES_PASSWORD=pass123 -e POSTGRES_USER=kirill -e POSTGRES_DB=ozon -d -p 5432:5432 -v $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres

  db-stop:
    desc: "Stop postgres"
    cmds:
      - sudo docker stop pgdocker

  start:
    desc: "Start server"
    cmds:
      - go run cmd/server/main.go

  gen:
    desc: "Generate resolvers"
    cmds:
      - rm -rf generated.go models_gen.go resolver.go
      - go get github.com/99designs/gqlgen@v0.17.64
      - go run github.com/99designs/gqlgen generate --config internal/graphql/gqlgen.yml